#!/usr/bin/env bash

# gnx -- algorithms for graphs and networks
# Copyright (C) 2016 Minh Van Nguyen <mvngu.name AT gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

# Analyze the code coverage of gnx.
#
# You must run this script from the gnx root directory.

PROJECT=gnx && declare -r PROJECT
UTILDIR=$(dirname "$0") && declare -r UTILDIR
ROOTDIR=$(dirname "$UTILDIR") && declare -r ROOTDIR

cd "$ROOTDIR"
test -f autogen.sh || {
    echo "Run this script in the top-level ${PROJECT} directory."
    exit 1
}

COVDIR=$(realpath ../"${PROJECT}-coverage") && declare -r COVDIR
if [[ -d "$COVDIR" ]]; then
    rm -rf "$COVDIR"
fi
mkdir -p "$COVDIR"
OUTPUT="${COVDIR}/coverage.info" && declare -r OUTPUT
OUTDIR="${COVDIR}/html" && declare -r OUTDIR

#############################################################################
# start here
#############################################################################

"$UTILDIR"/gitcmd --root "$ROOTDIR" --add
"$UTILDIR"/gxbuild --gassert yes --gcov yes                                \
        && make check                                                      \
        && lcov --capture                                                  \
                --directory "$ROOTDIR"                                     \
                --output-file "$OUTPUT"                                    \
        && genhtml "$OUTPUT" --output-directory "$OUTDIR"
errno="$?"
"$UTILDIR"/gitcmd --root "$ROOTDIR" --checkout

if [[ "$errno" = 0 ]]; then
    chromium-browser --incognito "$OUTDIR"/index.html
fi
