#!/usr/bin/env bash

# gnx -- algorithms for graphs and networks
# Copyright (C) 2016 Minh Van Nguyen <mvngu.name AT gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

# Compile gnx from scratch and run the test suite.
#
# You must run this script from the gnx root directory.

PROJECT=gnx && declare -r PROJECT
UTILDIR=$(dirname "$0") && declare -r UTILDIR
ROOTDIR=$(dirname "$UTILDIR") && declare -r ROOTDIR

cd "$ROOTDIR"
test -f autogen.sh || {
    echo "Run this script in the top-level ${PROJECT} directory."
    exit 1
}

"$UTILDIR"/gitcmd --root "$ROOTDIR" --add
"$UTILDIR"/gxbuild --gassert yes --gcov no && make check
retval="$?"
"$UTILDIR"/gitcmd --root "$ROOTDIR" --checkout
exit "$retval"
